const express = require('express');
var userRoute = require('./users');
var dbRoute = require('./db');
const dbCableRouter = require('./dbCable');
const dbTraceRouter = require('./dbTrace');
const dbSpRouter = require('./dbSp');
const dbSpFcsRouter = require('./dbSpFcs');
const dbTpFcsRouter = require('./dbTpFcs');
const dbTpPortsRouter = require('./dbTpPorts');

const dbTpRouter = require('./dbTp');
const dbLogRouter = require('./dbLog');
const dbChangeStateRouter = require('./changeState');
const dbAddSpItem = require('./addSpItem');
const dbAddTpItem = require('./addTpItem');
const dbAddCableItem = require('./addCableItem');
const dbUpdateSpItem = require('./updateSpItem');
const dbUpdateTpItem = require('./updateTpItem');
const dbUpdateCableItem = require('./updateCableItem');
const dbGetConnections = require('./getConnections');
const dbAddConnections = require('./addConnections');
const dbUpdateConnectionsFix = require('./updateConnectionsFix');
const dbUpdateConnections = require('./updateConnections');
const dbRemoveConnections = require('./removeConnections');
const dbNewProject = require('./dbNewProject');
const dbUpdateSplicesSp = require('./updateSplicesSp');
const dbUpdateSplicesTp = require('./updateSplicesTp');
const dbDeleteSpItem = require('./deleteSpItem');
const dbDeleteTpItem = require('./deleteTpItem');
const dbDeleteCableItem = require('./deleteCableItem');
const dbUpdateSpLatLng = require('./updateSpLatLng');
const dbUpdateTpLatLng = require('./updateTpLatLng');
const dbUpdateCableLatLng = require('./updateCableLatLng');
const dbFewSpRouter = require('./getFewSp');
const dbGetProjectOptions = require('./getProjectOptions');
const dbUpdateProjectOptions = require('./setProjectOptions');
const UploadPicture = require('./uploadPicture');
const downloadPicture = require('./downloadPicture');
const deletePicture = require('./deletePicture');

const UploadDocument = require('./uploadDocument');
const downloadDocument = require('./downloadDocument');
const deleteDocument = require('./deleteDocument');

const getHistory = require('./getHistory');
const updateSeqNumbers = require('./updateSeqNumbers');

//const dbFewTpRouter = require('./getFewTp');
//const dbFewCabRouter = require('./getFewCab');
const apiV1Route = new express.Router();


apiV1Route.use('/users', userRoute);
apiV1Route.use('/data-bases', dbRoute);
apiV1Route.use('/db-cables', dbCableRouter);
apiV1Route.use('/db-sp', dbSpRouter);
apiV1Route.use('/db-getTrace', dbTraceRouter);
apiV1Route.use('/getFewSp', dbFewSpRouter);
//apiV1Route.use('/getFewTp', dbFewTpRouter);
//apiV1Route.use('/getFewCab', dbFewCabRouter);
apiV1Route.use('/db-sp-fcs', dbSpFcsRouter);
apiV1Route.use('/db-tp', dbTpRouter);
apiV1Route.use('/db-tp-fcs', dbTpFcsRouter);
apiV1Route.use('/db-tp-ports', dbTpPortsRouter);
apiV1Route.use('/log-file', dbLogRouter);
apiV1Route.use('/change-state', dbChangeStateRouter);
apiV1Route.use('/addSpItem', dbAddSpItem);
apiV1Route.use('/addTpItem', dbAddTpItem);
apiV1Route.use('/addCableItem', dbAddCableItem);
apiV1Route.use('/updateSpItem', dbUpdateSpItem);
apiV1Route.use('/updateTpItem', dbUpdateTpItem);
apiV1Route.use('/updateCableItem', dbUpdateCableItem);
apiV1Route.use('/getConnections', dbGetConnections);
apiV1Route.use('/updateConnections', dbUpdateConnections);
apiV1Route.use('/updateConnectionsFix', dbUpdateConnectionsFix);
apiV1Route.use('/updateConnectionsAdd', dbAddConnections);
apiV1Route.use('/updateConnectionsRemove', dbRemoveConnections);
apiV1Route.use('/newProject', dbNewProject);
apiV1Route.use('/updateSplicesSp', dbUpdateSplicesSp);
apiV1Route.use('/updateSplicesTp', dbUpdateSplicesTp);
apiV1Route.use('/deleteSpItem', dbDeleteSpItem);
apiV1Route.use('/deleteTpItem', dbDeleteTpItem);
apiV1Route.use('/deleteCableItem', dbDeleteCableItem);
apiV1Route.use('/updateSpLatLng', dbUpdateSpLatLng);
apiV1Route.use('/updateTpLatLng', dbUpdateTpLatLng);
apiV1Route.use('/updateCableLatLng', dbUpdateCableLatLng);
apiV1Route.use('/db-project-options', dbGetProjectOptions);
apiV1Route.use('/updateProjectOptions', dbUpdateProjectOptions);
apiV1Route.use('/uploadPicture', UploadPicture);
apiV1Route.use('/getPicture', downloadPicture);
apiV1Route.use('/deletePicture', deletePicture);
apiV1Route.use('/uploadDocument', UploadDocument);
apiV1Route.use('/getDocument', downloadDocument);
apiV1Route.use('/deleteDocument', deleteDocument);
apiV1Route.use('/getHistory/', getHistory);
apiV1Route.use('/updateSeqNumbers/', updateSeqNumbers);

module.exports = apiV1Route